apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferron-ingress-poc
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: ferron-ingress-poc
spec:
  ports:
    - appProtocol: http
      name: http
      port: 80
      protocol: TCP
      targetPort: http
    #- appProtocol: https
    #  name: https
    #  port: 443
    #  protocol: TCP
    #  targetPort: https
  selector:
    app: ferron-ingress-poc
  type: LoadBalancer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ferron-ingress-poc
rules:
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ferron-ingress-poc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ferron-ingress-poc
subjects:
  - kind: ServiceAccount
    name: ferron-ingress-poc
    namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ferron-ingress-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ferron-ingress-poc
  template:
    metadata:
      labels:
        app: ferron-ingress-poc
    spec:
      serviceAccountName: ferron-ingress-poc
      containers:
        - name: controller
          image: dorianniemiec/ferron-ingress-poc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
